name: Backup Supabase

on:
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - run: supabase db dump --db-url "postgresql://postgres:ZRAgency3008@db.kftgzfvpblimiredvaqo.supabase.co:5432/postgres" --file backup.sql
      - name: Upload backup
        uses: actions/upload-artifact@v4
        with:
          name: supabase-backup
          path: backup.sql
